services:
  postgres:
    image: postgres:15
    container_name: banking-postgres
    environment:
      POSTGRES_DB: bankingdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    networks:
      - banking-network

  mongodb:
    image: mongo:6
    container_name: banking-mongo
    ports:
      - "27017:27017"
    networks:
      - banking-network

  app:
    build: .
    container_name: banking-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/bankingdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_DATA_MONGODB_URI: mongodb://mongodb:27017/bankingaudit
      JWT_SECRET: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      JWT_EXPIRATION: 86400000
    depends_on:
      - postgres
      - mongodb
    networks:
      - banking-network

networks:
  banking-network:
    driver: bridge