# Cloud PostgreSQL
spring.datasource.url=jdbc:postgresql://34.45.236.91:5432/bankingdb
spring.datasource.username=postgres
spring.datasource.password=postgres123
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# MongoDB Atlas
spring.data.mongodb.uri=mongodb+srv://bankinguser:banking123@banking-cluster.lz06j59.mongodb.net/bankingaudit?appName=banking-cluster

# App
spring.application.name=banking-api
server.port=8080
spring.docker.compose.enabled=false
spring.main.allow-circular-references=true